- name: Set up source user
  hosts: tag_webserver
  connection: ssh
  sudo: yes

  tasks:
    - name: Create source user
      user: name=source uid=1100 group=users

    - name: Fix sudoers file to allow sudo -u
      replace: >
        dest=/etc/sudoers
        regexp='^(\w+) ALL=NOPASSWD: ALL$'
        replace='\1 ALL=(ALL) NOPASSWD: ALL'
        validate='visudo -cf %s'

