- name: Build pencilcode code
  hosts: tag_webserver
  connection: ssh
  sudo: yes
  sudo_user: source
  tasks:
    - name: sync to latest code
      git: >
        repo=https://github.com/PencilCode/pencilcode.git
        dest=/home/source/pencilcode
      register: sync
    - name: update to current npm depenencies
      npm: path=/home/source/pencilcode
      register: install
    - name: rebuild pencilcode
      script: grunt chdir=/home/source/pencilcode
      when: sync|changed or install|changed

- name: Clone source packages
  hosts: tag_webserver
  connection: ssh
  sudo: yes
  sudo_user: source
  tasks:
    - git: >
        repo=https://github.com/PencilCode/pencilcode.git
        dest=/home/source/pencilcode
    - npm: path=/home/source/pencilcode

    - git: >
        repo=https://github.com/PencilCode/pencilcode.git
        dest=/home/source/staging
    - npm: path=/home/source/staging

    - git: >
        repo=https://github.com/PencilCode/fish.git
        dest=/home/source/fish
    - npm: path=/home/source/fish

    - git: >
        repo=https://github.com/PencilCode/codegym.git
        dest=/home/source/codegym
    - npm: path=/home/source/codegym

    - git: >
        repo=https://github.com/PencilCode/blog.git
        dest=/home/source/blog
    - npm: path=/home/source/blog

    - git: >
        repo=https://github.com/PencilCode/reference.git
        dest=/home/source/reference
    - npm: path=/home/source/reference

