- name: Create instance(s)
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    machine_type: n1-standard-1 # default
    image: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20170330
    service_account_email: ansible-service@paris-code.iam.gserviceaccount.com
    credentials_file: /etc/ansible/keys/service-key.json
    project_id: paris-code

  tasks:
    - name: Launch instances
      gce:
          instance_names: nfs
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          tags: nfs
      register: gce

    - name: Create log disks
      gce_pd:
          name: "{{ item.name }}-log"
          instance_name: "{{ item.name }}"
          mode: READ_WRITE
          size_gb: 10
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          zone: "{{ item.zone }}"
      with_items: "{{ gce.instance_data }}"

    - name: Create data disks
      gce_pd:
          name: "{{ item.name }}-data"
          instance_name: "{{ item.name }}"
          mode: READ_WRITE
          size_gb: 100
          disk_type: pd-ssd
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          zone: "{{ item.zone }}"
      with_items: "{{ gce.instance_data }}"

    - name: Create backup disk
      gce_pd:
          name: "{{ item.name }}-backup"
          instance_name: "{{ item.name }}"
          mode: READ_WRITE
          size_gb: 200
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          zone: "{{ item.zone }}"
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=5 timeout=60
      with_items: "{{ gce.instance_data }}"

    - name: Add host to groupname
      add_host: hostname={{ item.private_ip }} groupname=launched
      with_items: "{{ gce.instance_data }}"

    - name: reset known-hosts for ips
      command: ssh-keygen -R {{ item.private_ip }}
      with_items: "{{ gce.instance_data }}"

    - name: registering new known-host for ips
      shell: ssh-keyscan -H {{ item.private_ip }} >> ~/.ssh/known_hosts
      with_items: "{{ gce.instance_data }}"

    - name: reset known-hosts for names
      command: ssh-keygen -R {{ item.name }}
      with_items: "{{ gce.instance_data }}"

    - name: registering new known-host for names
      shell: ssh-keyscan -H {{ item.name }} >> ~/.ssh/known_hosts
      with_items: "{{ gce.instance_data }}"

- name: Set up disks
  hosts: launched
  connection: ssh
  become: yes
  tasks:
    - name: Set up filesystem for log disks
      filesystem: >
        fstype=ext4
        dev=/dev/disk/by-id/google-{{ ansible_hostname }}-log
        opts="-E lazy_itable_init=0,lazy_journal_init=0,discard"

    - name: Set up filesystem for data disks
      filesystem: >
        fstype=ext4
        dev=/dev/disk/by-id/google-{{ ansible_hostname }}-data
        opts="-b size=512 -N 10000000 -E lazy_itable_init=0,lazy_journal_init=0,discard"

    - name: Set up filesystem for backup disks
      filesystem: >
        fstype=ext4
        dev=/dev/disk/by-id/google-{{ ansible_hostname }}-backup
        opts="-b size=512 -N 20000000 -E lazy_itable_init=0,lazy_journal_init=0,discard"

    - name: Mount log disks
      mount: >
        name=/var/log
        fstype=ext4
        src=/dev/disk/by-id/google-{{ ansible_hostname }}-log
        state=mounted
      notify: restart rsyslog

    - name: Mount data disks
      mount: >
        name=/data
        fstype=ext4
        src=/dev/disk/by-id/google-{{ ansible_hostname }}-data
        state=mounted

    - name: Set up file permissions
      file: path=/data owner=www-data group=www-data state=directory

    - name: Set up subdirectories
      file: >
        path=/mnt/datadisk/{{ item }}
        state=directory mode=755 owner=www-data group=www-data
      with_items:
        - cache
        - data
        - proxycache

    - name: Mount backup disks
      mount: >
        name=/backup
        fstype=ext4
        src=/dev/disk/by-id/google-{{ ansible_hostname }}-backup
        state=mounted

    - name: Set up file permissions
      file: path=/backup owner=www-data group=www-data state=directory

  handlers:
    - name: restart rsyslog
      service: name=rsyslog state=restarted

- name: Set up nfs
  hosts: launched
  connection: ssh
  gather_facts: no
  become: yes

  roles:
    - role: geerlingguy.nfs
      nfs_exports:
        - /data *(rw,sync,no_subtree_check)
        - /backup *(ro,sync,no_subtree_check)

- name: Disable mlocate
  hosts: launched
  connection: ssh
  gather_facts: no
  become: yes

  tasks:
    - name: Change permission of cron.daily mlocate to disable execution.
      file: /etc/cron.daily/mlocate mode=a-x

- name: Set up rsnapshot
  hosts: launched
  connection: ssh
  gather_facts: no
  become: yes
  
  tasks:
    - name: Install rsnapshot
      apt: name=rsnapshot state=latest

    - name: Configure rsnapshot
      copy: src=files/rsnapshot.conf dest=/etc/rsnapshot.conf

    - name: Configure rsnapshot cron
      copy: src=files/rsnapshot.cron dest=/etc/cron.d/rsnapshot

