- name: Install packages
  hosts: tag_webserver
  gather_facts: no
  connection: ssh
  sudo: yes

  tasks:
    - name: Install https support for apt
      apt: name=apt-transport-https update_cache=yes

    - name: Add nodesource signing key
      apt_key: >
        url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        id=68576280

    - name: Add nodesource apt repository
      apt_repository: >
        repo='deb https://deb.nodesource.com/node_0.12 wheezy main'

    - name: Install build tools
      apt: name=build-essential

    - name: Install nginx
      apt: name=nginx state=latest default_release=wheezy-backports

    - name: Install uwsgi-python
      apt: name=uwsgi-plugin-python

    - name: Install nodejs
      apt: name=nodejs

    - name: Install git
      apt: name=git

    - name: Install libfontconfig1
      apt: name=libfontconfig1

    - name: Install vim
      apt: name=vim

    - name: Install grunt
      npm: name=grunt global=yes production=yes
