- name: Delete web instances
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: vars/gcp_config.yml

  tasks:
    - name: Gather instance template info
      gcp_compute_instance_template_info:
        filters:
        - name = {{ gcp_web_template }}
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes: "{{ gcp_scopes }}"
      register: instancetemplate

    - name: Delete backend service
      gcp_compute_backend_service:
        name: "{{ gcp_web_service }}"
        health_checks:
        - "{{ gcp_web_healthcheck }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes: "{{ gcp_scopes }}"
        state: absent

    - name: Delete instance group manager
      gcp_compute_instance_group_manager:
        name: "{{ gcp_web_group }}"
        base_instance_name: "{{ gcp_web_instance }}"
        instance_template: "{{ instancetemplate.resources[0] }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes: "{{ gcp_scopes }}"
        state: absent
