- name: Create instance(s)
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    machine_type: n1-standard-1 # default
    image: backports-debian-7-wheezy
    service_account_email: 670662678080-v4dlk7smudbfr0rbc2n5mcb2mnsdbqpb@developer.gserviceaccount.com
    pem_file: /etc/ansible/keys/service-key.pem
    project_id: paris-code

  tasks:
    - name: Launch instances
      gce:
          instance_names: web1,web2
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          service_account_email: "{{ service_account_email }}"
          pem_file: "{{ pem_file }}"
          project_id: "{{ project_id }}"
          tags: webserver
      register: gce

    - debug: msg="instance data {{ gce.instance_data }}"

    - name: Create log disks
      gce_pd:
          name: "{{ item.name }}-log-1"
          instance_name: "{{ item.name }}"
          mode: READ_WRITE
          size_gb: 20
          service_account_email: "{{ service_account_email }}"
          pem_file: "{{ pem_file }}"
          project_id: "{{ project_id }}"
          zone: "{{ item.zone }}"
      with_items: gce.instance_data

    - name: Create data disks
      gce_pd:
          name: "{{ item.name }}-data-1"
          instance_name: "{{ item.name }}"
          mode: READ_WRITE
          size_gb: 10
          service_account_email: "{{ service_account_email }}"
          pem_file: "{{ pem_file }}"
          project_id: "{{ project_id }}"
          zone: "{{ item.zone }}"
      with_items: gce.instance_data

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=5 timeout=60
      with_items: gce.instance_data

    - name: Add host to groupname
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: gce.instance_data

- name: Set up disks
  hosts: launched
  connection: ssh
  sudo: yes
  tasks:
    - name: Set up filesystem for log disks
      filesystem: >
        fstype=ext4
        dev=/dev/disk/by-id/google-{{ ansible_hostname }}-log-1
        opts="-E lazy_itable_init=0,lazy_journal_init=0"

    - name: Set up filesystem for data disks
      filesystem: >
        fstype=ext4
        dev=/dev/disk/by-id/google-{{ ansible_hostname }}-data-1
        opts="-E lazy_itable_init=0,lazy_journal_init=0"

    - name: Mount log disks
      mount: >
        name=/var/log
        fstype=ext4
        src=/dev/disk/by-id/google-{{ ansible_hostname }}-log-1
        state=mounted
      notify: restart rsyslog

    - name: Mount data disks
      mount: >
        name=/mnt/datadisk
        fstype=ext4
        src=/dev/disk/by-id/google-{{ ansible_hostname }}-data-1
        state=mounted
  handlers:
    - name: restart rsyslog
      service: name=rsyslog state=restarted
