# Uses vars:
# repo - the URL of the repo to build
# dir - the name of the directory under /home/source
# force_build - true to rebuild everything

- name: sync {{ dir }} to latest code
  git: >
    repo={{ repo }}
    dest=/home/source/{{ dir }}
  sudo_user: source
  register: sync
- name: update {{ dir }} to current npm depenencies
  npm: path=/home/source/{{ dir }}
  sudo_user: source
  register: install
- name: rebuild {{ dir }}
  command: npm run build
  sudo_user: source
  args:
    chdir: /home/source/{{ dir }}
  when: sync|changed or install|changed or force_build
